server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  cache:
    type: redis
  cache-name: redis-cache
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/music
    username: core
    password: 12345678
    driverClassName: org.postgresql.Driver
hibernate:
  type:
    wrapper_array_handling: ALLOW
security:
  basic:
    enabled: false